### ISSUE TITLE
Doesn't work for HTTPS request

### ISSUE THREAD

**Issue by josenobile** [Gachl/Virtual-Hosts-Chrome-Extension#10]
Hi,

Because the hostname is sent when the TCP/SSL handshake is made, adding/modifying the http host header has no effect in what website is being served by the web server

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
