### ISSUE TITLE
Extension Stopped Working in Chrome - ERR_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by davelit** [Gachl/Virtual-Hosts-Chrome-Extension#11]
The Virtual Hosts extension stopped working in Chrome. Root cause seems to be that Chromium now [prohibits setting the "Host" header](https://github.com/chromium/chromium/blob/b2254b38369f4f8ce8685b7a82dee1251f6cea22/services/network/url_loader.cc#L679-L683).

This extension is still very valuable to me and more than [25K other people](https://chrome.google.com/webstore/detail/virtual-hosts/aiehidpclglccialeifedhajckcpedom). Despite extensive search I haven't found an alternative solution.

Therefore, please consider [submitting this extension to Firefox Add-ons](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on). I verified that it's [compatible with Firefox](https://www.extensiontest.com/) and [installed it temporarily](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox). Everything works as expected. So, no code changes are required, just a re-submission to Firefox Add-ons.

Thank you so much for everything!

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
