### ISSUE TITLE
Host is set on all requests

### ISSUE THREAD

**Issue by Gachl** [Gachl/Virtual-Hosts-Chrome-Extension#2]
The Host header is set on all requests. This may be problematic for pages that include external scripts like JQuery hosted on Google which will also receive a rewritten Host header.

**Comment by mcarver** [comment]
@Gachl,

I've rewrote the extension in my repo to include this functionality and others.

Functionality:
- Redirects vhost domain to the vhost IP.
- Adds Host header to requests for vhost IP.
- Skips requests that aren't for the vhost domain or vhost IP.
- Syncs with Chrome Storage for persistence.

Other changes:
- Updated README for instructions.
- Updated manifest, incremented version to 1.1.

Take a look at my changes and pull them or let me know if I'm on a different path and I'll package up a separate extension for the Chrome Store:

https://github.com/mcarver/Virtual-Hosts-Chrome-Extension

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
