### ISSUE TITLE
Multiple VHosts support

### ISSUE THREAD

**Issue by merces** [Gachl/Virtual-Hosts-Chrome-Extension#5]
Wouldn't be nice if we can add how many VHost-IP pairs we want? :)

By the way, thank you @Gachl @mcarver @Zacqary for contributing to this!

**Comment by garymgordon** [comment]
I agree. I would really like to be able to add multiple pairs.  Maybe at least 10. But the more the better. Thank you.  Gary Gordon

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
