### ISSUE TITLE
Problem with AJAX requests

### ISSUE THREAD

**Issue by javansolo** [Gachl/Virtual-Hosts-Chrome-Extension#7]
Hello
AJAX jquery requests do not work
Please check thanks

**Comment by belgirlaz** [comment]
I am having the same issue.  Ajax requests do not work.  Please advise.

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
