### ISSUE TITLE
hostname and parameter are getting replaced

### ISSUE THREAD

**Issue by plachco** [Gachl/Virtual-Hosts-Chrome-Extension#8]
Say I have VHost domain: google  and VHost IP: 216.58.217.78 and set to enabled
I type in the address bar of the browser:
http://google/?q=google    (search for the term "google" using google)

the url gets redirected to 
http://216.58.217.78?q=216.58.217.78
instead of
http://216.58.217.78?q=google

for reasons beyond me, the background.js' onBeforeRequestHandler gets called twice, so the details.url.replace switches out both matches. 
The tweak below of checking that the index is < 10, makes this glitch go away:
    onBeforeRequestHandler = function(details) {
      if(settings.enabled){
        var index=details.url.indexOf(settings.domain);
        if ((index > -1) && (index < 10)) {
          return { redirectUrl: details.url.replace(settings.domain, settings.ip) };
        }
      }
    };
The index < 10 is just to accommodate for both http://  and https:// 
I am not sure if you are still updating this thing, but it would be awesome if the chrome store version had this fix. I figure I'd ask before cooking up a new version. thanks!

**Comment by Gachl** [comment]
Usually a valid url to rewrite contains a tld and not just a hostname; this not very sophisticated script only does a text replacement and doesn't parse the url for where the hostname is.

Are you sure that you don't want to use http://google.com/search?q=google and replace google.com with the IP (that should result in http://216.58.217.78/search?q=google).

Unfortunately I haven't updated the chrome store version in forever, you're probably better off modifying and using the version from git, sorry. Maybe one day when I feel bored and masochistic enough to do javascript again I'll fix the open issues.

**Comment by plachco** [comment]
The google example was just an easy way to explain it, actually my use case
is a secured cross domain proxy, and when its all said and done the request
contains the hostname in one of the parameters. I patched up my own version
of the extension and put it in a shared folder for my team to install as an
unpacked extension. This will work out just fine for my needs.
Great work on this extension, clever and simple enough for outsiders to
understand and pitch in. I hope javascript is kind to you in your future
endeavors :)

**Comment by lucasengel** [comment]
Is rewriting the expected behavior? Shouldn't we be able to browse google.com seeing that URL?
I mean, if the mapping rule is (google.com -> 111.111.111.111) shouldn't we be able to see google address while browsing the IP server?

**Comment by Gachl** [comment]
@lucasengel I'm not sure I understand you correctly, or maybe my brain is breaking a little.

As far as I remember the rewriting is IP -> host, not host -> IP. The point is so that you don't have to have a  DNS to resolve a domain to your test server IP, it's done locally. When you browse 111.111.111.111 it should add all headers and stuff so that the web server thinks you've entered google.com.

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
