### ISSUE TITLE
Vhost is activated incorrectly if vhost domain is substring of current URL

### ISSUE THREAD

**Issue by aneeshd16** [Gachl/Virtual-Hosts-Chrome-Extension#9]
If the vhost domain is a substring (not exact match) of the current url, it is replacing the matched substring and incorrectly proxying the request.

For example:
vhost ip: 127.0.0.1
vhost domain - x.com
Current domain in URL - yx.com

Url now becomes `y127.0.0.1`

Issue seems to be on https://github.com/Gachl/Virtual-Hosts-Chrome-Extension/blob/master/background.js#L14-L15

**Comment by Gachl** [comment]
Overwriting the Host header in Chrome is not possible anymore.

The plugin was rewritten to work with Firefox and support multiple hosts.

https://addons.mozilla.org/firefox/addon/vhost-simulator/
